<a href="https://colab.research.google.com/github/YannMjl/AI-764/blob/main/RNNArchitecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Common RNN Notations
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

# Create some random data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

# Defining our model
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [6]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

[[-2.148694   1.6168525]]


In [5]:
#Print the model summary
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 5)                 45        
                                                                 
 dense_1 (Dense)             (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
#. let's check out the model weights
model.layers[1].get_weights()

[array([[ 0.8421313 ,  0.7019271 ,  0.6597051 , -0.61591995, -0.5434624 ],
        [ 0.40838748,  0.31492585,  0.3489198 ,  0.47080642, -0.33159494],
        [-0.76457936,  0.31931454, -0.5779588 , -0.05227596, -0.3785795 ]],
       dtype=float32),
 array([[ 0.9167247 ,  0.3041575 ,  0.04165179,  0.25550547, -0.00928857],
        [ 0.06957582,  0.05174902,  0.84867394, -0.4586256 , -0.24879017],
        [-0.26417112,  0.3265076 ,  0.0666246 ,  0.5213804 , -0.73981756],
        [-0.28819796,  0.75381154,  0.20279482,  0.12327179,  0.5407297 ],
        [-0.04394019, -0.47955343,  0.48213413,  0.66132134,  0.31352583]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [10]:
a,b=model.layers[2].get_weights()
print(a,b)

[[-0.27361125  0.43872476]
 [ 0.80581415 -0.86788857]
 [ 0.39964962 -0.6107789 ]
 [-0.91975415 -0.19855702]
 [-0.35629088  0.6107465 ]] [0. 0.]


In [12]:
# We will do manual calculation of RNN
# Assigning Weight variables

Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [13]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

In [14]:
for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[-2.1486938   1.61685233]
